### ISSUE TITLE
Support for DB First?

### ISSUE THREAD

**Issue by daveshapiro** [jbogard/EntityFramework.Filters#7]
Is it possible to provide support for DB first models?

**Comment by hyankov** [comment]
I am not sure why this issue ended up as "Closed". OP made very valid point and I am currently in the same situation.

I am implementing a solution which has to integrate with an existing database over which I have no control. So EDMX (database-first) it is. But I can't register the filters, because **OnModelCreating** is setup to throw an exception (as designed) and I can't use **DbConfiguration** either (please correct me if I am wrong).

The tools provided by the EDMX are inadequate, in my opinion and don't overlap in any way with what this project is solving.

So, any ideas?

**Comment by csensoft** [comment]
I do not know why this is closed when there is no actual solution to do the described problem.

**Comment by jbogard** [comment]
Probably because the last time I committed to this codebase was 5 years ago?

🤷‍♂️ 🤷‍♂️ 🤷‍♂️ 🤷‍♂️ 🤷‍♂️
